const storyContent = {
    bg: "assets/stories/backgrounds/rainy_jungle.jpg",
    assets: {
        "曼松_虚弱": "assets/stories/manshoon/weak.png",
        "曼松_暴戾": "assets/stories/manshoon/violent.png",
        "曼松_震惊": "assets/stories/manshoon/shocked.png",
        "曼松_傲慢": "assets/stories/manshoon/arrogant.png",
        "曼松_平静": "assets/stories/manshoon/calm.png",
        "凛_平静": "assets/stories/rin/calm.png",
        "凛_冷漠": "assets/stories/rin/cold.png",
        "凛_思考": "assets/stories/rin/thinking.png",
        "凛_微笑": "assets/stories/rin/smile.png"
    },
    lines: [
        { speaker: "旁白", emotion: "", text: "暴雨如注，狂风撕扯着巨蕨的阔叶。" },
        { speaker: "旁白", emotion: "", text: "曼松靠在一截覆满青苔的断墙上，胸口剧烈起伏。他那身标志性的黑色法袍已经被利刃割得支离破碎，暗红色的血迹混着雨水，顺着贤者法杖的杖身蜿蜒流下。" },
        { speaker: "曼松", emotion: "曼松_暴戾", text: "“傻逼红袍人……该死的巫妖……”" },
        { speaker: "旁白", emotion: "", text: "他咬着牙，眼底闪过一丝暴戾。法术位空了，连高阶卷轴都在刚才那场针对红袍法师的突围战中消耗殆尽。" },
        { speaker: "旁白", emotion: "", text: "最致命的是，拜阿瑟瑞克的福，现在的他，只有这一条命。" },
        { speaker: "旁白", emotion: "", text: "死了，就是真的死了。" },
        { speaker: "旁白", emotion: "", text: "就在他试图从次元袋里摸索最后一瓶治疗药水时......" },
        { speaker: "旁白", emotion: "", text: "原本狂乱的暴雨在他前方十米处突兀地静止了，仿佛有一道无形的屏障将混乱隔绝在外。" },
        { speaker: "旁白", emotion: "", text: "几张画满鲜红符文的纸人在雨中诡异地漂浮着，既没有被淋湿，也没有被风吹走，而是像游鱼一样，绕着一个身影缓缓盘旋。" },
        { speaker: "旁白", emotion: "", text: "那是一个穿着红白巫女服的年轻女性，手里拿着一柄御币，脚尖离地三寸，悬浮在泥泞之上。她的黑发柔顺地垂在身后，与曼松狼狈的模样形成了惨烈的对比。" },
        { speaker: "旁白", emotion: "", text: "曼松瞳孔骤缩。他下意识地想要触发法杖，却惊恐地发现——空间被锁死了。周围的一百二十尺内，魔网如同凝固的水泥，任何传送尝试，即使是迷踪步，都会直接挤碎施法者的内脏。" },
        { speaker: "？？？", emotion: "凛_平静", text: "“初次见面，久仰大名。”" },
        { speaker: "旁白", emotion: "", text: "那个女人开口了，声音清冷、平稳，带着一种让人极度不适的、居高临下的礼貌。" },
        { speaker: "？？？", emotion: "凛_平静", text: "“散塔林会的首领，我是洛萨维亚帝国第三远征军上校，神代凛。”" },
        { speaker: "旁白", emotion: "", text: "曼松强行挺直了脊背，试图维持住大法师的威仪，尽管他的肺部正像风箱一样发出破损的嘶鸣。" },
        { speaker: "曼松", emotion: "曼松_震惊", text: "“异界人！！！”" },
        { speaker: "曼松", emotion: "曼松_震惊", text: "“你们封锁了海岸线还不够，现在连丛林里的孤魂野鬼都要抓？”" },
        { speaker: "旁白", emotion: "", text: "神代凛微微偏头，身边的纸人轻轻震颤，发出一阵窸窸窣窣的摩擦声。" },
        { speaker: "神代凛", emotion: "凛_冷漠", text: "“只是恰巧路过，感应到了高强度的魔力溃散。”" },
        { speaker: "旁白", emotion: "", text: "她的目光扫过曼松还在流血的左肋。" },
        { speaker: "神代凛", emotion: "凛_冷漠", text: "“您看起来状况非常糟糕，曼松先生。”" },
        { speaker: "曼松", emotion: "曼松_傲慢", text: "“我刚刚杀了一队红袍法师，还有上百只不死生物。”" },
        { speaker: "曼松", emotion: "曼松_傲慢", text: "“如果你想动手，那你最好重新评估一下站在你面前的是谁。”" },
        { speaker: "神代凛", emotion: "凛_平静", text: "“吾辈当然清楚您的实力。全盛时期的您，确实值得吾辈认真对待。”" },
        { speaker: "旁白", emotion: "", text: "神代凛微微欠身，行了一个无可挑剔的礼。" },
        { speaker: "神代凛", emotion: "凛_冷漠", text: "“但恕我直言，以您现在的状态——魔力枯竭、肉体濒临崩溃……”" },
        { speaker: "旁白", emotion: "", text: "她顿了顿，语气诚恳得像是在提建议，" },
        { speaker: "神代凛", emotion: "凛_冷漠", text: "“如果您执意要反抗，恐怕很难在吾辈面前撑过三分钟。”" },
        { speaker: "曼松", emotion: "曼松_虚弱", text: "‘三分钟？我现在连6秒都撑不住。’" },
        { speaker: "曼松", emotion: "曼松_虚弱", text: "‘如果克隆术还在，我一定当场掰掉这根法杖，来一场华丽的自爆，给这个不知天高地厚的女人上一课。’" },
        { speaker: "曼松", emotion: "曼松_虚弱", text: "‘但现在不行。绝对不行。’" },
        { speaker: "旁白", emotion: "", text: "曼松深吸了一口气，脸上那副狰狞的杀意像潮水般退去，取而代之的是一种令人捉摸不透的深沉。" },
        { speaker: "旁白", emotion: "", text: "他缓缓将法杖重重地顿在泥泞中，当作拐杖支撑着身体。" },
        { speaker: "曼松", emotion: "曼松_平静", text: "“三分钟……哼。”" },
        { speaker: "曼松", emotion: "曼松_平静", text: "“看来你们的情报工作做得不错，连我不喜欢做无用功这一点都调查清楚了。”" },
        { speaker: "神代凛", emotion: "凛_平静", text: "“明智的选择。”" },
        { speaker: "旁白", emotion: "", text: "神代凛手中的御币轻轻垂下，周围那种压得人喘不过气来的灵压稍微收敛了一些，" },
        { speaker: "神代凛", emotion: "凛_平静", text: "“那么，您是打算投降了吗？作为战俘，帝国会给予您符合身份的待遇。”" },
        { speaker: "曼松", emotion: "曼松_傲慢", text: "“战俘？”" },
        { speaker: "旁白", emotion: "", text: "曼松挑起一边的眉毛" },
        { speaker: "曼松", emotion: "曼松_平静", text: "“别用那么低级的词汇侮辱我，也别侮辱你自己的野心，上校。”" },
        { speaker: "曼松", emotion: "曼松_平静", text: "“我知道你们想要什么。你们封锁传送，攻占港口，但你们对费伦一无所知。你们就像闯进瓷器店的大象，空有力量，却不知道哪里藏着金子，哪里藏着毒蛇。”" },
        { speaker: "旁白", emotion: "", text: "他向前迈了半步，身边的纸人立刻发出警告的嘶鸣，但曼松无视了它们。" },
        { speaker: "曼松", emotion: "曼松_平静", text: "“杀了我也许能给你的履历添上一笔，‘击毙散塔林会首领’，听起来不错。但然后呢？”" },
        { speaker: "曼松", emotion: "曼松_平静", text: "“你会得到一具尸体，和整个散塔林会永无止境的报复。在这个充满魔法的世界里，暗杀防不胜防。”" },
        { speaker: "旁白", emotion: "", text: "曼松顿了顿，观察着神代凛的表情。她依然面无表情，但没有打断他。" },
        { speaker: "曼松", emotion: "曼松_平静", text: "“但如果你带我走，不是作为战俘，而是作为……合作者。”" },
        { speaker: "曼松", emotion: "曼松_平静", text: "“我可以把整个散塔林会的情报网交给你。楚尔特的古代地图、红袍法师的据点分布、甚至是深水城的政治丑闻。”" },
        { speaker: "曼松", emotion: "曼松_平静", text: "“你想升职，对吧？”" },
        { speaker: "旁白", emotion: "", text: "神代凛沉默了片刻。她身边的纸人停止了盘旋，乖顺地贴回了她的袖口。" },
        { speaker: "神代凛", emotion: "凛_思考", text: "“您很敏锐，曼松先生。”" },
        { speaker: "旁白", emotion: "", text: "她的声音依旧礼貌，但多了一丝真实的兴趣，" },
        { speaker: "神代凛", emotion: "凛_思考", text: "“但吾辈如何保证，在您恢复魔力之后，不会反咬一口呢？“" },
        { speaker: "神代凛", emotion: "凛_思考", text: "“毕竟，关于您的背叛史，情报部也有厚厚的一沓文件。”" },
        { speaker: "曼松", emotion: "曼松_平静", text: "“因为我是个实用主义者。”" },
        { speaker: "旁白", emotion: "", text: "曼松指了指周围的黑暗丛林，" },
        { speaker: "曼松", emotion: "曼松_平静", text: "“现在，你是刀俎，我是鱼肉。而且，红袍法师不会放过我。在彻底解决萨扎斯坦的威胁之前，我们的利益是一致的。更何况……”" },
        { speaker: "旁白", emotion: "", text: "曼松扯动嘴角，露出一个极其虚伪却又充满诱惑力的微笑。" },
        { speaker: "曼松", emotion: "曼松_平静", text: "“这世上没有永远的敌人，只有永恒的利益。你们异界人如此强大，与其当你们的死敌，不如借你们的势，帮我清理一些费伦本土的垃圾。这笔交易，对你我来说，都是稳赚不赔。”" },
        { speaker: "旁白", emotion: "", text: "神代凛看着眼前这个即便狼狈至极，却依然试图操控局势的男人。她思考了大约五秒钟——" },
        { speaker: "神代凛", emotion: "凛_微笑", text: "“很有说服力。”" },
        { speaker: "神代凛", emotion: "凛_微笑", text: "“但这需要一点保障。只是一个简单的定位与预警咒文。如果您离开了吾辈的一定范围，或者积蓄了攻击性的高阶魔力，它会给您一点小小的……提醒。”" },
        { speaker: "旁白", emotion: "", text: "神代凛轻轻挥动御币，一张散发着柔和白光的符咒凭空出现，缓缓飘向曼松。" },
        { speaker: "旁白", emotion: "", text: "曼松任由符咒贴在了自己破烂的长袍上。" },
        { speaker: "曼松", emotion: "曼松_平静", text: "“公平合理。”" },
        { speaker: "旁白", emotion: "", text: "曼松淡淡地评价道，仿佛这只是一次普通的商业签署。" },
        { speaker: "神代凛", emotion: "凛_微笑", text: "“那么，欢迎加入第三远征军的临时阵营，曼松先生。”" },
        { speaker: "旁白", emotion: "", text: "她转身，示意曼松跟上。" },
        { speaker: "神代凛", emotion: "凛_平静", text: "“不远处有吾辈的临时营地。”" },
        { speaker: "旁白", emotion: "", text: "曼松拄着法杖，步履蹒跚地跟在那个漂浮的背影后面。他看着神代凛那毫无防备的后背，眼底的阴鸷一闪而过，随即被完美的伪装覆盖。" },
        { speaker: "曼松", emotion: "曼松_虚弱", text: "‘活着就好。’" },
        { speaker: "曼松", emotion: "曼松_虚弱", text: "‘只要活着，就有翻盘的机会。’" },
        { speaker: "曼松", emotion: "曼松_暴戾", text: "‘草包异界人，等我找到机会修复了克隆术……我会让你知道什么是费伦大法师的手段’" }
    ]
};
